-- StudyIG CTO - Database Schema Initialization Migration
--
-- TARGET: Supabase (PostgreSQL)
-- PURPOSE: Isolates the AI coding assistant's memory space inside its own schema,
--          preventing collision with any production StudyIG tables in the "public" schema.
-- SAFETY: Idempotent statements (using IF NOT EXISTS) make this safe to rerun.

-- 1. Create pgcrypto extension safely in public or default extensions schema
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Create the dedicated schema for StudyIG CTO if it does not already exist
CREATE SCHEMA IF NOT EXISTS studyig_cto;

-- 3. Idempotent creation of PostgreSQL ENUM types inside the studyig_cto schema
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'chat_role' AND typnamespace = 'studyig_cto'::regnamespace) THEN
        CREATE TYPE studyig_cto.chat_role AS ENUM ('system', 'user', 'assistant');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status' AND typnamespace = 'studyig_cto'::regnamespace) THEN
        CREATE TYPE studyig_cto.task_status AS ENUM ('todo', 'in_progress', 'review', 'done', 'backlog');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_priority' AND typnamespace = 'studyig_cto'::regnamespace) THEN
        CREATE TYPE studyig_cto.task_priority AS ENUM ('low', 'medium', 'high', 'critical');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bug_status' AND typnamespace = 'studyig_cto'::regnamespace) THEN
        CREATE TYPE studyig_cto.bug_status AS ENUM ('open', 'investigating', 'resolved', 'closed');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'decision_impact' AND typnamespace = 'studyig_cto'::regnamespace) THEN
        CREATE TYPE studyig_cto.decision_impact AS ENUM ('low', 'medium', 'high', 'critical');
    END IF;
END $$;

-- 4. Create projects table
CREATE TABLE IF NOT EXISTS studyig_cto.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    repository_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Create repositories table (GitHub repo configs linked to projects)
CREATE TABLE IF NOT EXISTS studyig_cto.repositories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    owner TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    branch TEXT NOT NULL DEFAULT 'main',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_owner_repo UNIQUE (owner, repo_name)
);

-- 6. Create architecture table (codebase architecture diagrams and tech specs)
CREATE TABLE IF NOT EXISTS studyig_cto.architecture (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    component_name TEXT NOT NULL,
    description TEXT NOT NULL,
    tech_stack TEXT[] NOT NULL DEFAULT '{}',
    design_patterns TEXT[] NOT NULL DEFAULT '{}',
    file_paths TEXT[] NOT NULL DEFAULT '{}',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Create tasks table (project-management tasks generated by the AI or engineer)
CREATE TABLE IF NOT EXISTS studyig_cto.tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status studyig_cto.task_status NOT NULL DEFAULT 'todo',
    priority studyig_cto.task_priority NOT NULL DEFAULT 'medium',
    assigned_to TEXT,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Create bugs table (unresolved issues, debugging history, and errors)
CREATE TABLE IF NOT EXISTS studyig_cto.bugs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    file_path TEXT,
    line_number INTEGER,
    status studyig_cto.bug_status NOT NULL DEFAULT 'open',
    severity studyig_cto.task_priority NOT NULL DEFAULT 'medium',
    reproduction_steps TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Create decisions table (Architectural Decision Records - ADRs)
CREATE TABLE IF NOT EXISTS studyig_cto.decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    context TEXT NOT NULL,
    decision TEXT NOT NULL,
    consequences TEXT NOT NULL,
    impact studyig_cto.decision_impact NOT NULL DEFAULT 'medium',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Create prompts table (custom templates or specialized instructions)
CREATE TABLE IF NOT EXISTS studyig_cto.prompts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    purpose TEXT NOT NULL,
    prompt_text TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. Create conversations table (chat threads for organized team messaging)
CREATE TABLE IF NOT EXISTS studyig_cto.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'New Conversation',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. Create assistant_memories table (the conversation messages)
CREATE TABLE IF NOT EXISTS studyig_cto.assistant_memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES studyig_cto.projects(id) ON DELETE CASCADE,
    conversation_id UUID REFERENCES studyig_cto.conversations(id) ON DELETE CASCADE,
    role studyig_cto.chat_role NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Safe migration checks for pre-existing assistant_memories tables (ensures conversation_id exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'studyig_cto' 
          AND table_name = 'assistant_memories' 
          AND column_name = 'conversation_id'
    ) THEN
        ALTER TABLE studyig_cto.assistant_memories 
        ADD COLUMN conversation_id UUID REFERENCES studyig_cto.conversations(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'studyig_cto' 
          AND table_name = 'assistant_memories' 
          AND column_name = 'project_id'
    ) THEN
        ALTER TABLE studyig_cto.assistant_memories 
        ADD COLUMN project_id UUID REFERENCES studyig_cto.projects(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 13. Enable Row Level Security (RLS) on all tables for maximum safety
--     RLS is active, which blocks all public access. The backend service-role key
--     bypasses RLS automatically, ensuring only authenticated systems can connect.
ALTER TABLE studyig_cto.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.repositories ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.architecture ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.bugs ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE studyig_cto.assistant_memories ENABLE ROW LEVEL SECURITY;

-- 14. Establish database indexes for foreign keys and frequently queried columns
CREATE INDEX IF NOT EXISTS idx_repositories_project_id ON studyig_cto.repositories(project_id);
CREATE INDEX IF NOT EXISTS idx_architecture_project_id ON studyig_cto.architecture(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON studyig_cto.tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON studyig_cto.tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON studyig_cto.tasks(priority);
CREATE INDEX IF NOT EXISTS idx_bugs_project_id ON studyig_cto.bugs(project_id);
CREATE INDEX IF NOT EXISTS idx_bugs_status ON studyig_cto.bugs(status);
CREATE INDEX IF NOT EXISTS idx_decisions_project_id ON studyig_cto.decisions(project_id);
CREATE INDEX IF NOT EXISTS idx_conversations_project_id ON studyig_cto.conversations(project_id);
CREATE INDEX IF NOT EXISTS idx_assistant_memories_project_id ON studyig_cto.assistant_memories(project_id);
CREATE INDEX IF NOT EXISTS idx_assistant_memories_conversation_id ON studyig_cto.assistant_memories(conversation_id);

-- 15. Set up an automated updated_at trigger helper function if it does not exist
CREATE OR REPLACE FUNCTION studyig_cto.update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 16. Attach trigger to update timestamp columns automatically
DROP TRIGGER IF EXISTS update_projects_modtime ON studyig_cto.projects;
CREATE TRIGGER update_projects_modtime BEFORE UPDATE ON studyig_cto.projects FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_repositories_modtime ON studyig_cto.repositories;
CREATE TRIGGER update_repositories_modtime BEFORE UPDATE ON studyig_cto.repositories FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_architecture_modtime ON studyig_cto.architecture;
CREATE TRIGGER update_architecture_modtime BEFORE UPDATE ON studyig_cto.architecture FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_tasks_modtime ON studyig_cto.tasks;
CREATE TRIGGER update_tasks_modtime BEFORE UPDATE ON studyig_cto.tasks FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_bugs_modtime ON studyig_cto.bugs;
CREATE TRIGGER update_bugs_modtime BEFORE UPDATE ON studyig_cto.bugs FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_decisions_modtime ON studyig_cto.decisions;
CREATE TRIGGER update_decisions_modtime BEFORE UPDATE ON studyig_cto.decisions FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_prompts_modtime ON studyig_cto.prompts;
CREATE TRIGGER update_prompts_modtime BEFORE UPDATE ON studyig_cto.prompts FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

DROP TRIGGER IF EXISTS update_conversations_modtime ON studyig_cto.conversations;
CREATE TRIGGER update_conversations_modtime BEFORE UPDATE ON studyig_cto.conversations FOR EACH ROW EXECUTE FUNCTION studyig_cto.update_modified_column();

-- Documentation Comments
COMMENT ON SCHEMA studyig_cto IS 'Isolated database schema containing persistent memory tables for the StudyIG CTO AI Agent.';
COMMENT ON TABLE studyig_cto.projects IS 'Stores the codebases and repositories indexed by StudyIG CTO.';
COMMENT ON TABLE studyig_cto.repositories IS 'Stores GitHub repository configuration parameters linked to project workspaces.';
COMMENT ON TABLE studyig_cto.architecture IS 'Contains analyzed tech stack details, design patterns, and components diagrams.';
COMMENT ON TABLE studyig_cto.tasks IS 'Logs project management tasks generated automatically or manually.';
COMMENT ON TABLE studyig_cto.bugs IS 'Tracks software bugs, error occurrences, and logs reproduction steps.';
COMMENT ON TABLE studyig_cto.decisions IS 'Hosts Architectural Decision Records (ADR) documenting implementation paths.';
COMMENT ON TABLE studyig_cto.prompts IS 'Maintains version-controlled system instructions and chat templates.';
COMMENT ON TABLE studyig_cto.conversations IS 'Groups assistant messaging threads to segment topics dynamically.';
COMMENT ON TABLE studyig_cto.assistant_memories IS 'Holds the messages (user inputs, assistant answers, system setups) within conversations.';
